version: "3"

services:
    app:
      build: .
      container_name: app-mutual-challenge
      command: npm run dev
      ports:
        - "8080":8080
      env_files:
        - .env
      volumes:
        - .:/usr/app
    mutual-challenge-db:
      image: nouchka/sqlite3
      container_name: mutual-challenge-db,
      restart: always